language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install coveralls
script:
  coverage run --source=. --omit tests/\* tests/function.py
  py.test tests/function.py
after_success:
  coveralls
