language: python

#sudo: required
#dist: trusty

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 3.4
    - os: linux
      dist: trusty
      sudo: required
      python: 3.5
    - os: linux
      dist: trusty
      sudo: required
      python: 3.5-dev
    - os: linux
      dist: trusty
      sudo: required
      python: nightly
    - os: osx
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y clang-format-3.5 ; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   brew update                              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   brew install python3                     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   brew install clang-format                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   sudo easy_install pip                    ; fi
install:
  - sudo pip install coveralls
script:
  - coverage run -m py.test ./tests/
after_success:
  - coveralls

notifications:
  slack:
    rooms:
      secure: GefpYpO238WSWzZbmhwweyOh/6wnbZGPtl9S7C8sA6FeNB34xwVyGgTmm+exXbXWEmhqo3vA53V5qzLKM4gqO5krba4tUtoeawNa2kUPR6IfN+GgPZItxaFU54FLEpvSJAHKroSws8GT419g/uzkJpZnyavWRFj2egNusU9DPyWnIWCQnN+Vpy1kIUpXQ+gAGfF8bxUJJdXjfu9VkDms0QKVIESJJpMfyUtT/UlTu+WqGWfOWDomF7JAUDCVDeRdb4BKIE0c8q2fTNZdQnPaTYrqotYf95CqoRVKNWrVMldVSqoL6iHIjSW45kvCq/FtV4WMkAoj9sHz0RxHX1sWJT9dCs6IXDKk30gurMjdFn+bnBWazNvNZ/97FTXnrU/ze0yXCfKnyyYSpa7+QPzt5LxLNbNSExzSwr4uBCwEzjO5OwF2Ag9PMYHGa61LxpdoSNMCN2+IXwkGF++rxZa/UrmSgH7Z6QBRSfII2gv2NGftJhcD6YWvlh8ce5kyMCqgQcc4F1fAPePHhzuslwA+HuEg2crsC3lrEtyeT3Mc/QFTfM5LgrgTQTsYjRmH+cscAwEKWfXENFy1Dw0TzyIzyKBgJ/wETmxqwW3gJ9jjHlKGYaLL7suG9gi3B5jE9O63z7j7KN1rcYmdZALKEoZmWI2yLeohCepVd47hEGzknzE=
